{% set name = "eth-account" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f66ecb7bc52569924dfaf4a9add501b1c2a4901eec74e3c0598cd26d0971777

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - bitarray >=2.4.0,<3
    - eth-abi >=3.0.1
    - eth-keyfile >=0.6.0,<0.7.0
    - eth-keys >=0.4.0,<0.5
    - eth-rlp >=0.3.0,<1
    - eth-utils >=2.0.0,<3
    - hexbytes >=0.1.0,<1
    - rlp >=1,<4

test:
  imports:
    - eth_account
    - eth_account._utils
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-account
  summary: 'eth-account: Sign Ethereum transactions and messages with local private keys'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
